version: "3.8"

services:
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: xtemple
      MONGO_INITDB_ROOT_PASSWORD: mongopass
  web:
    env_file:
      - ./flask_app/.env
    build: '.'
    ports:
      - '8080:8080'
    depends_on:
      - db